database:
  host: 127.0.0.1
  port: 3306
  username: root
  password:
  database: cutepet
  charset: utf8

redis:
  host: localhost
  port: 6379
  password:
  DB: 0

app:
  port: 8080
  debug: true
  log_level: debug
  secret_key: testsecret
  env: local

email_service:
  host: smtp.163.com
  port: 465
  username: xingtianwuganqi123@163.com
  password: DQHEPDTSYPAVKEFB

api_keys:
  google: test-google-api-key
  facebook: test-facebook-api-key