database:
  host: mysql
  port: 3306
  username: cutepetpro
  password: YhKiwmATtRJ2Jhme
  database: project4_prod
  charset: utf8mb4

redis:
  host: redis
  port: 6379
  password:
  DB: 0

app:
  port: 8082
  debug: false
  log_level: info
  secret_key: testsecret
  env: production

# 添加日志配置
log:
  filename: "logs/app.log"
  max_size: 100    # 日志文件最大 100MB
  max_backups: 10  # 最多保留 10 个备份文件
  max_age: 30      # 文件最多保存 30 天
  compress: true   # 压缩旧文件

email_service:
  host: smtp.163.com
  port: 465
  username: xingtianwuganqi123@163.com
  password: DQHEPDTSYPAVKEFB

api_keys:
  google: test-google-api-key
  facebook: test-facebook-api-key
  qiniuAccessKey: 1vLUgTSJEyyElB_EFpsCzua84QJJqrtrPrueICw2
  qiniuSecretKey : QvOlYbG0my-CGh7nfjnBnOxVP1j3ClqhR1Ocf0Ug